#!/bin/sh

. /lib/functions.sh

export_host() {
        local section="$1"
        local _mac
        local _ip
        local _name

        config_get _mac "$section" mac
        config_get _ip "$section" ip
        config_get _name "$section" name

        echo add dhcp host
        [ -n "$_mac" ] && echo set dhcp.@host[-1].mac=$_mac
        [ -n "$_ip" ] && echo set dhcp.@host[-1].ip=$_ip
        [ -n "$_name" ] && echo set dhcp.@host[-1].name=\"$_name\"
}

config_load dhcp
config_foreach export_host host
